/**
 * @file oem_exporter.hpp
 * @brief CCSDS OEM (Orbit Ephemeris Message) exporter for HPOP
 *
 * Implements CCSDS 502.0-B-2 Orbit Data Messages standard
 */

#ifndef HPOP_EXPORT_OEM_EXPORTER_HPP
#define HPOP_EXPORT_OEM_EXPORTER_HPP

#include <string>
#include <vector>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <cmath>
#include <chrono>
#include <ctime>

namespace hpop_export
{

/**
 * @brief OEM export options
 */
struct OemExportOptions
{
    // Header information
    std::string originator = "HPOP_SYSTEM";
    std::string object_name = "UNKNOWN";
    std::string object_id = "UNKNOWN";
    std::string center_name = "EARTH";
    std::string ref_frame = "EME2000";        // EME2000 (J2000), ICRF, ITRF
    std::string time_system = "UTC";          // UTC, TDB, GPS

    // Optional metadata
    std::string start_time = "";              // Auto-generated if empty
    std::string stop_time = "";               // Auto-generated if empty
    std::string useable_start_time = "";
    std::string useable_stop_time = "";
    std::string interpolation = "LAGRANGE";
    int interpolation_degree = 7;

    // Format options
    int position_precision = 3;               // Decimal places [m]
    int velocity_precision = 9;               // Decimal places [m/s]
    bool include_covariance = false;
    bool include_acceleration = false;
};

/**
 * @brief Ephemeris state for OEM
 */
struct OemState
{
    double epoch_jd;           // Julian Date
    double x, y, z;            // Position [km]
    double vx, vy, vz;         // Velocity [km/s]

    // Optional
    double ax, ay, az;         // Acceleration [km/s^2]
};

/**
 * @brief CCSDS OEM exporter
 */
class OemExporter
{
public:
    OemExporter() = default;

    /**
     * @brief Export ephemeris to OEM file
     * @param filename Output filename
     * @param states Vector of ephemeris states
     * @param options Export options
     * @return true if successful
     */
    bool exportToFile(const std::string& filename,
                      const std::vector<OemState>& states,
                      const OemExportOptions& options = OemExportOptions())
    {
        std::ofstream file(filename);
        if (!file.is_open())
        {
            last_error_ = "Failed to open file: " + filename;
            return false;
        }

        writeOem(file, states, options);
        file.close();
        return true;
    }

    /**
     * @brief Export ephemeris to string
     */
    std::string exportToString(const std::vector<OemState>& states,
                               const OemExportOptions& options = OemExportOptions())
    {
        std::ostringstream ss;
        writeOem(ss, states, options);
        return ss.str();
    }

    /**
     * @brief Get last error message
     */
    std::string getLastError() const { return last_error_; }

private:
    std::string last_error_;

    template<typename Stream>
    void writeOem(Stream& stream, const std::vector<OemState>& states,
                  const OemExportOptions& options)
    {
        // Write header
        writeHeader(stream, states, options);

        // Write metadata
        writeMetadata(stream, states, options);

        // Write data
        writeData(stream, states, options);
    }

    template<typename Stream>
    void writeHeader(Stream& stream, const std::vector<OemState>& states,
                     const OemExportOptions& options)
    {
        stream << "CCSDS_OEM_VERS = 2.0\n";
        stream << "COMMENT HPOP System - High Precision Orbit Propagator\n";
        stream << "COMMENT Generated by ROS2 HPOP Export Package\n";
        stream << "CREATION_DATE = " << getCurrentUtcTime() << "\n";
        stream << "ORIGINATOR = " << options.originator << "\n";
        stream << "\n";
    }

    template<typename Stream>
    void writeMetadata(Stream& stream, const std::vector<OemState>& states,
                       const OemExportOptions& options)
    {
        stream << "META_START\n";
        stream << "OBJECT_NAME = " << options.object_name << "\n";
        stream << "OBJECT_ID = " << options.object_id << "\n";
        stream << "CENTER_NAME = " << options.center_name << "\n";
        stream << "REF_FRAME = " << options.ref_frame << "\n";
        stream << "TIME_SYSTEM = " << options.time_system << "\n";

        // Time bounds
        if (!states.empty())
        {
            std::string start_time = options.start_time.empty()
                ? jdToIso8601(states.front().epoch_jd)
                : options.start_time;
            std::string stop_time = options.stop_time.empty()
                ? jdToIso8601(states.back().epoch_jd)
                : options.stop_time;

            stream << "START_TIME = " << start_time << "\n";
            stream << "STOP_TIME = " << stop_time << "\n";

            if (!options.useable_start_time.empty())
            {
                stream << "USEABLE_START_TIME = " << options.useable_start_time << "\n";
            }
            if (!options.useable_stop_time.empty())
            {
                stream << "USEABLE_STOP_TIME = " << options.useable_stop_time << "\n";
            }
        }

        stream << "INTERPOLATION = " << options.interpolation << "\n";
        stream << "INTERPOLATION_DEGREE = " << options.interpolation_degree << "\n";
        stream << "META_STOP\n";
        stream << "\n";
    }

    template<typename Stream>
    void writeData(Stream& stream, const std::vector<OemState>& states,
                   const OemExportOptions& options)
    {
        stream << "COMMENT Ephemeris data (position in km, velocity in km/s)\n";

        for (const auto& state : states)
        {
            // Epoch
            stream << jdToIso8601(state.epoch_jd);

            // Position [km]
            stream << std::fixed << std::setprecision(options.position_precision);
            stream << "  " << std::setw(15) << state.x;
            stream << "  " << std::setw(15) << state.y;
            stream << "  " << std::setw(15) << state.z;

            // Velocity [km/s]
            stream << std::fixed << std::setprecision(options.velocity_precision);
            stream << "  " << std::setw(18) << state.vx;
            stream << "  " << std::setw(18) << state.vy;
            stream << "  " << std::setw(18) << state.vz;

            // Optional acceleration
            if (options.include_acceleration)
            {
                stream << std::scientific << std::setprecision(9);
                stream << "  " << state.ax;
                stream << "  " << state.ay;
                stream << "  " << state.az;
            }

            stream << "\n";
        }
    }

    /**
     * @brief Get current UTC time as ISO 8601 string
     */
    std::string getCurrentUtcTime()
    {
        auto now = std::chrono::system_clock::now();
        auto time_t_now = std::chrono::system_clock::to_time_t(now);
        std::tm* gmt = std::gmtime(&time_t_now);

        std::ostringstream ss;
        ss << std::setfill('0');
        ss << (gmt->tm_year + 1900) << "-"
           << std::setw(2) << (gmt->tm_mon + 1) << "-"
           << std::setw(2) << gmt->tm_mday << "T"
           << std::setw(2) << gmt->tm_hour << ":"
           << std::setw(2) << gmt->tm_min << ":"
           << std::setw(2) << gmt->tm_sec << "Z";

        return ss.str();
    }

    /**
     * @brief Convert Julian Date to ISO 8601 string
     */
    std::string jdToIso8601(double jd)
    {
        // Convert JD to calendar date
        double z = std::floor(jd + 0.5);
        double f = jd + 0.5 - z;

        double a;
        if (z < 2299161)
        {
            a = z;
        }
        else
        {
            double alpha = std::floor((z - 1867216.25) / 36524.25);
            a = z + 1 + alpha - std::floor(alpha / 4);
        }

        double b = a + 1524;
        double c = std::floor((b - 122.1) / 365.25);
        double d = std::floor(365.25 * c);
        double e = std::floor((b - d) / 30.6001);

        int day = static_cast<int>(b - d - std::floor(30.6001 * e));
        int month = static_cast<int>((e < 14) ? e - 1 : e - 13);
        int year = static_cast<int>((month > 2) ? c - 4716 : c - 4715);

        // Time of day
        double day_fraction = f;
        int hour = static_cast<int>(day_fraction * 24);
        day_fraction = day_fraction * 24 - hour;
        int minute = static_cast<int>(day_fraction * 60);
        day_fraction = day_fraction * 60 - minute;
        double second = day_fraction * 60;

        std::ostringstream ss;
        ss << std::setfill('0');
        ss << year << "-" << std::setw(2) << month << "-" << std::setw(2) << day;
        ss << "T" << std::setw(2) << hour << ":" << std::setw(2) << minute;
        ss << ":" << std::fixed << std::setprecision(6) << std::setw(9) << second;

        return ss.str();
    }
};

} // namespace hpop_export

#endif // HPOP_EXPORT_OEM_EXPORTER_HPP
